micronaut:
  application:
    name: backend-service
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        frontend:
          allowed-origins:
            - "http://localhost:5173"  # Vite default port
            - "http://localhost:3000"  # Create React App default port
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
            - X-Requested-With
          allow-credentials: true
          max-age: 3600S

r2dbc:
  datasources:
    default:
      options:
        driver: pool
        protocol: postgres
        initialSize: 5
        maxSize: 35
        maxLifetime: PT280S
        maxIdleTime: PT240S
        maxAcquireTime: PT6S
        poolName: webcheckout-r2dbc
      schema-generate: CREATE
      dialect: POSTGRES
      db-type: postgres
      username: root
      password: root
      url: r2dbc:pool:postgresql://localhost:5432/khatabook

logger:
  levels:
    io.micronaut.data.query: DEBUG
    io.micronaut.data.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG